# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clipping_manager.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clippings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clipping',
                'verbose_name_plural': 'Clippings',
                'ordering': ('book',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='clipping',
            unique_together=set([('user', 'book', 'content')]),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('title', 'user')]),
        ),
    ]
