# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title'),
        ),
    ]
