# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0004_auto_20190701_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildelivery',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
