# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-09 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0006_auto_20190906_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildelivery',
            name='number_of_highlights',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Number of highlights to be sent per mail'),
        ),
    ]
