# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-13 09:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clipping_manager', '0007_auto_20190909_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='content_hash',
            field=models.CharField(max_length=100, null=True, verbose_name='Hash of the clipping'),
        ),
        migrations.AlterUniqueTogether(
            name='clipping',
            unique_together=set([('user', 'book', 'content_hash')]),
        ),
    ]
