# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0009_generate_clipping_content_hashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clippings', to='clipping_manager.Book', verbose_name='Book'),
        ),
    ]
