# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0010_auto_20190913_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='content_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hash of the clipping'),
        ),
    ]
