# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-07-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0012_data_generate_clipping_hashs'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
