# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-07-26 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0013_myclippingsfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myclippingsfiles',
            options={'verbose_name': 'MyClippings file', 'verbose_name_plural': 'MyClippings files'},
        ),
        migrations.AddField(
            model_name='myclippingsfiles',
            name='language_header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Accept-Language header'),
        ),
    ]
