# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2025-12-30 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0014_clipping_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='include_in_email',
            field=models.BooleanField(default=True, help_text='If disabled, highlights from this book will not be sent in email deliveries', verbose_name='Include in email delivery'),
        ),
    ]
