# -*- coding: utf-8 -*-
# Generated by OpenCode on 2026-07-20
from __future__ import unicode_literals

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_manager', '0015_book_include_in_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_content', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', verbose_name='Email content')),
                ('request_frequency', models.CharField(choices=[('never', 'Never'), ('every_email', 'Every email'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='never', max_length=20, verbose_name='Donation request frequency')),
                ('goal_amount', models.CharField(default='', max_length=100, verbose_name='Goal amount')),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, verbose_name='Progress percentage')),
            ],
            options={
                'verbose_name': 'Donation configuration',
                'verbose_name_plural': 'Donation configuration',
            },
        ),
        migrations.AddField(
            model_name='emaildelivery',
            name='donation_request_last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Donation request last sent at'),
        ),
    ]
